version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    restart: on-failure
    networks:
      - app_network
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - server
    command: npm run dev -- --hostname 0.0.0.0
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  server_node_modules:
  client_node_modules:
