# Generated by Django 5.2.1 on 2025-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprofile',
            name='body_mass',
            field=models.PositiveIntegerField(blank=True, help_text='Skeletal muscle mass in kg', null=True),
        ),
    ]
