# Generated by Django 5.2.1 on 2025-05-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_physicalprofile_body_mass'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('exercise', 'Exercise'), ('workout', 'Workout'), ('article', 'Article'), ('tutorial', 'Tutorial'), ('diet', 'Diet')], max_length=100)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Professional')], default=2)),
                ('equipment_required', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('target_muscles', models.CharField(blank=True, max_length=255)),
                ('embedding_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type'], name='api_fitness_content_67638d_idx'), models.Index(fields=['difficulty_level'], name='api_fitness_difficu_f1d977_idx')],
            },
        ),
    ]
